### ISSUE TITLE
LR train.py train error

### ISSUE THREAD

**Issue by Jacquelin803** [ma-zhiyuan/PersonalRecommendation#1]
```
def train_lr_model(train_file,model_coef,model_file):
    total_feature_num=118
    train_label = np.genfromtxt (train_file, dtype=np.int32, delimiter=",", usecols=-1)
    feature_list = range (total_feature_num)
    train_feature = np.genfromtxt (train_file, dtype=np.int32, delimiter=",", usecols=feature_list)
    lr_cf=LRCV(Cs=[1],penalty='l2',tol=0.0001,max_iter=500,cv=5).fit(train_feature,train_label)
    scores=lr_cf.scores_.values()[0]

```
  File "/Users/jacquelin/PycharmProjects/LR/production/train.py", line 27, in train_lr_model
    lr_cf=LRCV(Cs=[1],penalty='l2',tol=0.0001,max_iter=500,cv=5).fit(train_feature,train_label)
  File "/Users/jacquelin/anaconda3/lib/python3.6/site-packages/sklearn/linear_model/logistic.py", line 1754, in fit
    " class: %r" % classes[0])
ValueError: This solver needs samples of at least 2 classes in the data, but the data contains only one class: 0

could you run this train.py well？I can`t get the solution，please help me~~

**Comment by ma-zhiyuan** [comment]
This is due to too little training data. Please try some ways to extend the data.
Provide some references:
· [https://github.com/lensacom/sparkit-learn/issues/49](https://github.com/lensacom/sparkit-learn/issues/49)
  ```
   train_Z[:, 'y']._rdd.map(lambda x: np.unique(x).size).filter(lambda x: x < 2).count()
  ```
· used a scikitlearn utils module
   ```
    from sklearn.utils import shuffle
    X_shuf, Y_shuf = shuffle(X_transformed, Y)
   ````

**Comment by Jacquelin803** [comment]
> This is due to too little training data. Please try some ways to extend the data.
> Provide some references:
> · [lensacom/sparkit-learn#49](https://github.com/lensacom/sparkit-learn/issues/49)
> 
> ```
>  train_Z[:, 'y']._rdd.map(lambda x: np.unique(x).size).filter(lambda x: x < 2).count()
> ```
> · used a scikitlearn utils module
> 
> ```
>  from sklearn.utils import shuffle
>  X_shuf, Y_shuf = shuffle(X_transformed, Y)
> ```

thank you a lot~~the error disappeared ~~
